# Generated by Django 3.0.2 on 2020-02-15 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionFoodsAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('want', models.CharField(max_length=30, null=True)),
                ('action', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=30)),
                ('store', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('energie', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('tag', models.CharField(max_length=30)),
                ('str_tag', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_group', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('restaurant', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('energie', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
