# Generated by Django 3.0.2 on 2020-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0002_auto_20200218_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='画像ファイル')),
            ],
        ),
    ]
