# Generated by Django 3.0.2 on 2020-02-19 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0005_auto_20200219_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
