# Generated by Django 3.0.2 on 2020-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0007_auto_20200219_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
