# Generated by Django 3.0.2 on 2020-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0008_auto_20200219_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='画像ファイル'),
        ),
    ]
