# Generated by Django 3.0.2 on 2020-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0009_auto_20200219_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
