# Generated by Django 3.0.2 on 2020-02-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0010_foodimage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimage',
            old_name='title',
            new_name='url',
        ),
    ]
