# Generated by Django 3.0.2 on 2020-02-19 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0011_auto_20200219_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='eat_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
