# Generated by Django 3.0.3 on 2020-03-04 22:50

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('lognutsapp', '0015_foodimage_pfc_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='file',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
